server:
  port: 8081

# H2 DB
spring:
  h2:
    console:
      enabled: true
      path: '/h2-console-log'

  datasource:
    url: 'jdbc:h2:mem:local'


management:
  endpoints:
    web:
      exposure:
        include: '*'


application:
  param:
    value: 'application_param'
    config: {\'id\': 1, \'name\': frank, \'param\': param}
    users:
    -
      name: cindy
      password: 1q2w3e4r
    -
      {\'name\': david, \'password\': 1qaz2wsx}

user:
  file:
    path: ./src/main/resources/file/update/
    
    
# swagger uri
springdoc:
  swagger-ui:
    path: /swagger    